// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyopejbhrjikgpapygwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5b3BlamJocmppa2dwYXB5Z3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzk2ODQsImV4cCI6MjA3MDc1NTY4NH0.5Tkt1DBGbhUIXtQrCOousKxAXrxN5VjhCcIY5pioxOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});